project_id = "lzokflsidobsouzqxtta"

[functions.extract-listing-data]
verify_jwt = false


[functions.openai-analysis]
verify_jwt = false

[functions.demographics-analysis]
verify_jwt = false

[functions.energy-analysis]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.web-scraper]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.ai-deal-analysis]
verify_jwt = false