// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzokflsidobsouzqxtta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6b2tmbHNpZG9ic291enF4dHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjQyNzMsImV4cCI6MjA2NzQ0MDI3M30.ka3XP2-YIvvJbEKJYB5kP0yXVKo6gKSkGOeqF3H3Zxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});